#!/usr/bin/expect -f
set timeout -1
spawn ssh -o StrictHostKeyChecking=no root@49.50.139.88
expect "password:"
send "R4+r525MP5DiBi\r"

expect "# "
send "cd /root/portfolio && git pull origin main\r"

expect "# "
send "cp /root/portfolio/index.html /var/www/creator/index.html\r"

expect "# "
send "cp /root/portfolio/public/trive_organization.html /var/www/creator/trive_organization.html\r"

expect "# "
send "exit\r"

expect eof
